@url = http://localhost:8080/api/player



GET {{url}}/john@smith.com HTTP/1.1

###

#   "playerId": 1,
#   "displayName": null,
#   "username": "john@smith.com",
#   "password": "$2a$10$ntB7CsRKQzuLoKY3rfoAQen5nNyiC/U60wBsWnnYrtQQi8Z3IZzQa",
#   "enabled": true,
#   "accountBalance": 0,
#   "authorities": [],
#   "holeCards": null,
#   "position": null,
#   "playersAction": false,

PUT {{url}}/1 HTTP/1.1
Content-Type: application/json

{
    "playerId": 1,
    "username": "john@smith.com",
    "displayName": "sharklightning",
    "enabled": true,
    "accountBalance": 200,
    "authorities": [
        "ADMIN"
    ],
    "holeCards": [
    "ACE_OF_HEARTS",
    "KING_OF_DIAMONDS"
    ],
    "position": "SMALLBLIND",
    "playersAction": true
}

###

POST {{url}}/create-account HTTP/1.1
Content-Type: application/json

{
    "username": "bob@jones.com",
    "password": "P@ssw0rd!"
}

###

POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "bob@jones.com",
    "password": "P@ssw0rd!"
}

###

POST {{url}}/refresh-token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI4LWJpdC1wb2tlciIsInN1YiI6ImJvYkBqb25lcy5jb20iLCJhcHBfdXNlcl9pZCI6MywiYXV0aG9yaXRpZXMiOiJVU0VSIiwiZXhwIjoxNjg4MDU5ODMxfQ.Dm7_szRnxGm9xKORnvWcyTucDHc2nqVvFrAoyWZ0VZw